apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-new
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-new
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      name: web-new
      labels:
        app: web-new
    spec:
      volumes:
      - name: app
        emptyDir: {}
      containers:
      - name: web
        image: "slobanov/kubernetes-intro:1.0.0"
        volumeMounts:
        - mountPath: /app
          name: app
        readinessProbe:
          httpGet:
            path: /index.html
            port: 8000
        livenessProbe:
          tcpSocket:
            port: 8000
      initContainers:
      - name: init-web
        image: "busybox:1.31.0"
        command: ['sh', '-c', 'wget -O- https://raw.githubusercontent.com/express42/otus-platform-snippets/master/Module-02/Introduction-to-Kubernetes/wget.sh | sh']
        volumeMounts:
        - mountPath: /app
          name: app
